### ISSUE TITLE
Linux eslint issue

### ISSUE THREAD

**Issue by siarheiv** [Konnektid/eslint-config-konnektid#30]
Error log attached. Issue is within naming of module which works fine on Mac but fails on linux.

Cannot find module 'eslint-config-konnektid/rules/base/bestpractices'
Referenced from: eslint-config-konnektid/rules/base
Referenced from: eslint-config-konnektid
Referenced from: konnektid/babel
Referenced from: /home/sergey/WebstormProjects/Konnektid/src/apps/konnektid-graph/.eslintrc
Error: Cannot find module 'eslint-config-konnektid/rules/base/bestpractices'
Referenced from: eslint-config-konnektid/rules/base
Referenced from: eslint-config-konnektid
Referenced from: konnektid/babel
Referenced from: /home/sergey/WebstormProjects/Konnektid/src/apps/konnektid-graph/.eslintrc
    at Object.ModuleResolver.resolve (/home/sergey/.npm-global/lib/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/home/sergey/.npm-global/lib/node_modules/eslint/lib/config/config-file.js:473:33)
    at load (/home/sergey/.npm-global/lib/node_modules/eslint/lib/config/config-file.js:490:24)
    at /home/sergey/.npm-global/lib/node_modules/eslint/lib/config/config-file.js:386:36
    at Array.reduceRight (native)
    at applyExtends (/home/sergey/.npm-global/lib/node_modules/eslint/lib/config/config-file.js:363:28)
    at load (/home/sergey/.npm-global/lib/node_modules/eslint/lib/config/config-file.js:525:22)
    at /home/sergey/.npm-global/lib/node_modules/eslint/lib/config/config-file.js:386:36
    at Array.reduceRight (native)
    at applyExtends (/home/sergey/.npm-global/lib/node_modules/eslint/lib/config/config-file.js:363:28)

**Comment by rewop** [comment]
The problem is in this line: https://github.com/Konnektid/eslint-config-konnektid/blob/ac2b01e198c320cd3f2300d864c043b96ea16060/rules/base/index.js#L4

The rules tries to access `rules/base/bestpractices` but the file is called `rules/base/bestPractices`. Usual problem of sensitive case with mac fs.
